spring:
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          brokers: "localhost:9092"

server:
  port: 8086

default-currency: SEK

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]